
app:
    resource: "@AppBundle/Controller/DefaultController.php"
    type:     annotation


soduko:
    resource: "@AppBundle/Controller/SodukoController.php"
    type:     annotation
    prefix: /api

